# Generated by Django 4.0.3 on 2022-03-29 15:31

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 minute')),
                ('last', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.IntegerField()),
                ('cumulative_volume', models.IntegerField(null=True)),
                ('last_mid_before', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volume.symbol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('state', models.CharField(choices=[('C', 'Complete'), ('P', 'Pending'), ('A', 'Absent')], default='A', max_length=1)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volume.symbol')),
            ],
        ),
    ]
