# Generated by Django 4.0.3 on 2022-03-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataday',
            name='state',
            field=models.CharField(choices=[('C', 'Complete'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
