# Generated by Django 4.0.3 on 2022-03-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0002_alter_dataday_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
