# Generated by Django 4.0.3 on 2022-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0004_alter_dataday_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataday',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='minute',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['active', 'symbol']},
        ),
        migrations.AlterField(
            model_name='minute',
            name='last',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
