# Generated by Django 4.0.3 on 2022-04-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0005_alter_dataday_options_alter_minute_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='minute',
            name='volume_minu_time_c71f25_idx',
        ),
        migrations.AddIndex(
            model_name='minute',
            index=models.Index(fields=['time'], name='volume_minu_time_3b1bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='minute',
            index=models.Index(fields=['symbol', 'time'], name='volume_minu_symbol__97ddd6_idx'),
        ),
    ]
