# Generated by Django 4.0.3 on 2022-04-01 20:15

from django.db import migrations
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0006_remove_minute_volume_minu_time_c71f25_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 day'),
        ),
    ]
