# Generated by Django 4.0.3 on 2022-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0007_alter_minute_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataday',
            name='last_tried',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataday',
            name='state',
            field=models.CharField(choices=[('C', 'Complete'), ('P', 'Pending'), ('L', 'Live')], db_index=True, default='P', max_length=1),
        ),
    ]
