# Generated by Django 4.0.3 on 2022-05-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0008_dataday_last_tried_alter_dataday_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='type',
            field=models.CharField(choices=[('S', 'Stock'), ('I', 'Index')], db_index=True, default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='dataday',
            name='last_tried',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
