# Generated by Django 4.0.3 on 2022-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0010_alter_symbol_options_indexweight_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
