# Generated by Django 4.0.3 on 2022-05-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0011_symbol_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexweight',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='volume.symbol'),
        ),
        migrations.AlterField(
            model_name='indexweight',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
