# Generated by Django 4.0.3 on 2022-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0012_alter_indexweight_index_alter_indexweight_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexweight',
            name='weight',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
