# Generated by Django 4.0.3 on 2022-05-11 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0014_remove_symbol_slug_symbol_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='system',
        ),
        migrations.AddField(
            model_name='chart',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
