# Generated by Django 4.0.3 on 2022-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0015_remove_chart_system_chart_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('time', models.DateTimeField()),
                ('last_mid_before', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['added']},
        ),
        migrations.AddIndex(
            model_name='incomingprice',
            index=models.Index(fields=['symbol', 'time'], name='volume_inco_symbol_cb325e_idx'),
        ),
    ]
