# Generated by Django 4.0.3 on 2022-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0016_incomingprice_alter_chart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='colour',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
