# Generated by Django 4.0.3 on 2022-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0017_symbol_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
