# Generated by Django 4.0.3 on 2023-01-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0018_alter_symbol_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='slope',
            field=models.IntegerField(null=True),
        ),
    ]
