# Generated by Django 4.0.3 on 2023-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0021_correlation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlation',
            name='D',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='correlation',
            name='E',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='correlation',
            name='N',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='correlation',
            name='n',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='correlation',
            name='x_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='correlation',
            name='y_mean',
            field=models.FloatField(null=True),
        ),
    ]
