# Generated by Django 4.0.3 on 2023-02-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0022_correlation_d_correlation_e_correlation_n_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='D',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='E',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='N',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='n',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='x_mean',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='y_mean',
            field=models.FloatField(default=0, null=True),
        ),
    ]
