# Generated by Django 4.0.3 on 2023-02-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0023_alter_correlation_d_alter_correlation_e_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('group_type', models.CharField(choices=[('V', 'Volume Chart'), ('S', 'Slope Chart'), ('C', 'Correlation Table'), ('T', 'Slope Table'), ('O', 'Comparison Table')], db_index=True, max_length=1)),
                ('symbols', models.ManyToManyField(related_name='+', to='volume.symbol')),
            ],
            options={
                'ordering': ['added'],
            },
        ),
    ]
