# Generated by Django 4.0.3 on 2023-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0024_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('V', 'Volume Chart'), ('S', 'Slope Chart'), ('C', 'Correlation Table'), ('T', 'Slope Table')], db_index=True, max_length=1),
        ),
    ]
