# Generated by Django 4.0.3 on 2023-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0026_alter_group_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='api_symbol',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
