# Generated by Django 4.0.3 on 2023-06-19 12:03

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0027_symbol_api_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollingCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('data_type', models.CharField(choices=[('V', 'Volume'), ('S', 'Slope')], max_length=1)),
                ('window', models.IntegerField()),
                ('value', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volume.symbol')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddIndex(
            model_name='rollingcorrelation',
            index=models.Index(fields=['time'], name='volume_roll_time_fdb38e_idx'),
        ),
        migrations.AddIndex(
            model_name='rollingcorrelation',
            index=models.Index(fields=['symbol', 'time'], name='volume_roll_symbol__03d409_idx'),
        ),
        migrations.AddIndex(
            model_name='rollingcorrelation',
            index=models.Index(fields=['symbol', 'data_type', 'window', 'time'], name='volume_roll_symbol__866df5_idx'),
        ),
    ]
