# Generated by Django 4.0.3 on 2023-06-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0028_rollingcorrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('exchange', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('open', models.DateTimeField(null=True)),
                ('close', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
