# Generated by Django 4.0.3 on 2023-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0029_marketholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketholiday',
            name='close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketholiday',
            name='open',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
