# Generated by Django 4.0.3 on 2023-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0030_alter_marketholiday_close_alter_marketholiday_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('bool_value', models.BooleanField(null=True)),
                ('int_value', models.IntegerField(null=True)),
                ('string_value', models.TextField(blank=True, null=True)),
                ('float_value', models.FloatField(null=True)),
            ],
        ),
    ]
