# Generated by Django 4.0.3 on 2023-08-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volume', '0031_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='data_type',
            field=models.CharField(choices=[('B', 'boolean'), ('I', 'integer'), ('S', 'string'), ('F', 'float')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='bool_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
